---
# PB para criarção de LV no servidor ** especifique valor variavel -e HOST= na chamada
  - name: Cria LV de Servidores - CentOS
    hosts: "{{  HOST }}"
    become: yes
    roles: 
      - cria_lv

 
