---
# PB para criação de LV no servidor ** especifique valor variavel -e HOST= na chamada
# Etore Garone - garone.tux@gmail.com
  - name: Cria LV de Servidores - CentOS
    hosts: "{{  HOST }}"
    become: yes
    roles: 
      - cria_lv

 
